const colors = {
  dark: {
    text: "#FAFAFA",
    tint: "#7C5CFF",
    background: "#09090F",
    foreground: "#FAFAFA",
    card: "#0F0F1A",
    cardForeground: "#FAFAFA",
    primary: "#7C5CFF",
    primaryForeground: "#FFFFFF",
    secondary: "#1A1A2E",
    secondaryForeground: "#FAFAFA",
    muted: "#1A1A2E",
    mutedForeground: "#8080A8",
    accent: "#00D4FF",
    accentForeground: "#09090F",
    destructive: "#F25454",
    destructiveForeground: "#FFFFFF",
    border: "#22223A",
    input: "#1A1A2E",
    surface: "#12121F",
    userBubble: "#7C5CFF",
    aiBubble: "#0F0F1A",
    glowPurple: "#7C5CFF",
    glowCyan: "#00D4FF",
  },
  light: {
    text: "#0A0A1A",
    tint: "#6040F0",
    background: "#F5F5FF",
    foreground: "#0A0A1A",
    card: "#FFFFFF",
    cardForeground: "#0A0A1A",
    primary: "#6040F0",
    primaryForeground: "#FFFFFF",
    secondary: "#EEEEFF",
    secondaryForeground: "#0A0A1A",
    muted: "#EEEEFF",
    mutedForeground: "#6060A0",
    accent: "#0090CC",
    accentForeground: "#FFFFFF",
    destructive: "#E03030",
    destructiveForeground: "#FFFFFF",
    border: "#DDDDF0",
    input: "#EEEEFF",
    surface: "#F0F0FF",
    userBubble: "#6040F0",
    aiBubble: "#FFFFFF",
    glowPurple: "#6040F0",
    glowCyan: "#0090CC",
  },
  radius: 16,
};

export default colors;
